config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root 'home#index'
  get '/users', to: 'home#all_users'

  get '/admin', to: 'admin#index'

  get '/login', to: 'auth#login'
  get '/logout', to: 'auth#logout_user'
  post 'login/', to: 'auth#login_user'
  get '/register', to: 'auth#register'
  post '/register', to: 'auth#register_user'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/controllers/admin_controller.rb
class AdminController < ApplicationController
  def index
    redirect_to login_path unless logged_in?
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  class QueryError < StandardError; end

  helper_method :current_user, :logged_in?

  CurrentUser = RUGClient::Client.parse <<-'GRAPHQL'
    # All read requests are defined in a "query" operation
    query {
        currentUser {
            id
            username
            firstName
            lastName
        }
    }
  GRAPHQL

  def current_user
    @current_user = nil
    query = (query CurrentUser)
    @current_user = query.current_user if query
  end

  def logged_in?
    !!current_user
  end

  private

  # Public: Define request scoped helper method for making GraphQL queries.
  #
  # Examples
  #
  #   data = query(ViewerQuery)
  #   data.viewer.login #=> "josh"
  #
  # definition - A query or mutation operation GraphQL::Client::Definition.
  #              Client.parse("query { version }") returns a definition.
  # variables - Optional set of variables to use during the operation.
  #             (default: {})
  #
  # Returns a structured query result or raises if the request failed.
  def query(definition, variables = {})
    response = RUGClient::Client.query(definition, variables: variables, context: {})

    if response.errors.any?
      raise QueryError, response.errors[:data].join(', ')
    else
      response.data
    end
  end
end

app/controllers/auth_controller.rb
class AuthController < ApplicationController
  def login
    redirect_to root_path if logged_in?
  end

  LoginUserMutation = RUGClient::Client.parse <<-'GRAPHQL'
    # All read requests are defined in a "query" operation
      mutation($username: String!, $password: String!) {
        loginUser(input: {
          credentials: {
            username: $username,
            password: $password
          }
        })
        {
          token
          user {
            firstName
            lastName
            username
          }
          message
        }
      }
      
  GRAPHQL

  def login_user
    @username = params[:auth][:username].downcase
    @password = params[:auth][:password].downcase

    data = query LoginUserMutation, username: @username, password: @password

    if !data.login_user
      flash[:message] = 'The username or password is incorrect'
      flash[:type] = 'danger'
      redirect_to login_path
    else
      flash[:message] = data.login_user.message
      flash[:type] = 'success'
      redirect_to root_path
    end
  end

  LogoutUserMutation = RUGClient::Client.parse <<-'GRAPHQL'
    # All read requests are defined in a "query" operation
      mutation {
        logoutUser(input: {})
        {
          message
        }
      }
  GRAPHQL

  def logout_user
    redirect_to root_path unless logged_in?
    data = query LogoutUserMutation

    if !data.logout_user
      flash[:message] = 'There\'s some error occured. It\'s not your fault'
      flash[:type] = 'danger'
      redirect_to root_path
    else
      flash[:message] = data.logout_user.message
      flash[:type] = 'success'
      redirect_to root_path
    end
  end

  RegisterUserMutation = RUGClient::Client.parse <<-'GRAPHQL'
    # All read requests are defined in a "query" operation
      mutation($firstName: String!, $lastName: String!, $username: String!, $password: String!) {
        registerUser(input: {
          firstName: $firstName,
          lastName: $lastName,
          credentials: {
            username: $username,
            password: $password
          }
        })
        {
          user {
            firstName
            lastName
            username
          }
          message
        }
      }
  GRAPHQL

  def register
  end

  def register_user
    @first_name = params[:auth][:first_name].downcase
    @last_name = params[:auth][:last_name].downcase
    @username = params[:auth][:username].downcase
    @password = params[:auth][:password].downcase

    data = query RegisterUserMutation, firstName: @first_name, lastName: @last_name, username: @username,
                                       password: @password

    if !data.register_user
      flash[:message] = data.errors.messages[:registerUser].join(', ')
      flash[:type] = 'danger'
      redirect_to register_path
    else
      flash[:message] = data.register_user.message
      flash[:type] = 'success'
      redirect_to users_path
    end
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  # All queries MUST be assigned to constants and therefore be statically
  # defined. Queries MUST NOT be generated at request time.
  RandomUserQuery = RUGClient::Client.parse <<-'GRAPHQL'
    # All read requests are defined in a "query" operation
    query {
        randomUser {
            id
            username
            firstName
            lastName
        }
    }
  GRAPHQL

  AllUsers = RUGClient::Client.parse <<-'GRAPHQL'
    # All read requests are defined in a "query" operation
    query {
        users {
            id
            username
            firstName
            lastName
        }
    }
  GRAPHQL

  def index
    @random_user = (query RandomUserQuery).random_user
  end

  def all_users
    @users = (query AllUsers).users
  end
end

app/helpers/admin_helper.rb
module AdminHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/auth_helper.rb
module AuthHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/admin/index.html.erb
<header>Admin page</header>

<main>
    <h2>Add user</h2>
</main>

app/views/home/all_users.html.erb
<header>
    Random User Generator | All Users
</header>
<main>
<% if @users.any? %>
    <div class="users">
        <% for user in @users %>
            <div class="user">
                <h2 class="username"><%= user.username%></h2>
                <h4 class="first-name">First name: <%= user.first_name%></h4>
                <h4 class="last-name">Last name: <%= user.last_name%></h4>
            </div>
        <%end%>
    </div>
<% else %>
    <h2 class="username">There's no existing User yet. Add one?</h2>
<% end %>
    

    <a href="<%= root_path%>">Go back to homepage</a>

    <a href="<%= register_path%>">Add a User?</a>
</main>

app/views/home/index.html.erb
<header>
    Random User Generator
</header>
<main>
    <% if flash[:message] && flash[:type] %>    
        <p class="alert alert-<%= flash[:type] %> fade show" role="alert">
            <%= flash[:message] %>
        </p>
    <% end %>
    <% if @random_user %>
        <div class="user">
            <h2 class="username">@<%= @random_user.username%></h2>
            <h4 class="first-name">First name: <%= @random_user.first_name%></h4>
            <h4 class="last-name">Last name: <%= @random_user.last_name%></h4>
        </div>
    <% else %>
        <h2 class="username">There's no existing User yet. Add one?</h2>
    <% end %>
    
    <p>Currently logged in?: <strong><%= logged_in?.to_s.capitalize %></strong></p>

    <% if logged_in? %>
        <a href="<%= logout_path%>">Logout</a>
    <% else %>
        <a href="<%= login_path%>">Login</a>
    <% end %>
    <button onClick="window.location.reload();">RANDOM USER</button>

    <a href="<%= users_path%>">See all Users?</a>

    <a href="<%= register_path%>">Add a User?</a>
</main>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RUGClient</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
  <section>
    <%= yield %>
  </section>

  </body>
</html>